name: GitBook Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'

      - name: Log env
        run: node -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitBook CLI
        run: npm install gitbook-cli -g

      - name: Install GitBook Plugins
        run: gitbook install

      - name: Build
        run: gitbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: _book
